# Generated by Django 4.2.5 on 2023-11-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Air_Condition", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temperature_set", models.CharField(default="0", max_length=10)),
                ("temperature_out", models.CharField(default="0", max_length=10)),
                ("fan_model", models.CharField(default="制冷", max_length=20)),
                ("fan_speed", models.CharField(default="低速", max_length=10)),
                ("condition_set", models.CharField(default="关机", max_length=10)),
                ("current_time", models.TimeField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
