# Generated by Django 4.2.5 on 2023-11-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Air_Condition", "0003_alter_message_temperature_set"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="room_id",
            field=models.IntegerField(default=0),
        ),
    ]
